### ISSUE TITLE
Project Recommendation

### ISSUE THREAD

**Issue by hywang2002** [Zheng-Chong/Awesome-Try-On-Models#2]
A fresh project for both frontal-view and multi-view VTON, hope it can be added: https://github.com/hywang2002/MV-VTON

**Comment by hywang2002** [comment]
> A fresh project for both frontal-view and multi-view VTON, hope it can be added: https://github.com/hywang2002/MV-VTON

From AAAI 2025

**Comment by Zheng-Chong** [comment]
Great job! https://github.com/hywang2002/MV-VTON has been added to the repo!

**Comment by hywang2002** [comment]
> Great job! https://github.com/hywang2002/MV-VTON has been added to the repo!


Thank you for your attention !
